services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: cashfolio-redis
    build:
      context: .
      dockerfile: infra/cashfolio-redis/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_ADMIN_PASS=admin
      - REDIS_APP_PASS=app

volumes:
  pgdata:
  redis:
