#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$FLY_APP'
primary_region = '$FLY_PRIMARY_REGION'

[[services]]
  internal_port = 6379
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = $FLY_MIN_MACHINES_RUNNING
  processes = ["app"]
  
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = $FLY_MEMORY
  cpu_kind = '$FLY_CPU_KIND'
  cpus = $FLY_CPUS

[mounts]
  source = "data"
  destination = "/data"