#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$FLY_APP'
primary_region = '$FLY_PRIMARY_REGION'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = $FLY_MIN_MACHINES_RUNNING
  processes = ['app']

 [[vm]]
  memory = $FLY_MEMORY
  cpu_kind = '$FLY_CPU_KIND'
  cpus = $FLY_CPUS

[deploy]
  release_command = "pnpm --filter cashfolio-app exec prisma migrate deploy"

[env]
  CANONICAL_HOSTNAME = '$CANONICAL_HOSTNAME'
  BASE_URL = '$BASE_URL'
  COOKIE_DOMAIN = '$COOKIE_DOMAIN'
  LOGTO_APP_ID = '$LOGTO_APP_ID'
  LOGTO_ENDPOINT = '$LOGTO_ENDPOINT'