name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: 22
  FLYCTL_VERSION: 0.3.193
#   FRONTEND_INTERNAL_PORT: 3000
#   CMS_INTERNAL_PORT: 3001

jobs:
  version:
    name: "Generate version"
    uses: felixmokross/webplatform/.github/workflows/export.version.yml@main
    with:
      release: ${{ inputs.release }}

  cashfolio-app-build-push:
    name: "cashfolio-app: Build and Push"
    runs-on: ubuntu-latest
    needs: [version]
    outputs:
      image: ${{ steps.image-name.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - name: Setup
        uses: felixmokross/webplatform/.github/actions/setup@main
      - name: Set version on cashfolio-app
        run: |
          pnpm version ${{ needs.version.outputs.version }} --git-tag-version false
        working-directory: apps/cashfolio-app
      - name: Get cashfolio-app image name
        id: image-name
        run: |
          IMAGE_NAME=${{ vars.FLY_CASHFOLIO_APP_STAGING_APP }}
          IMAGE_TAG=v${{ needs.version.outputs.version_with_sha }}
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "image=registry.fly.io/$IMAGE_NAME:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
      - name: Build and push cashfolio-app Docker image
        run: |
          flyctl deploy \
            --app ${{ steps.image-name.outputs.image_name }} \
            --config apps/cashfolio-app/fly.build.toml \
            --build-only \
            --image-label ${{ steps.image-name.outputs.image_tag }} \
            --label org.opencontainers.image.version=${{ steps.image-name.outputs.image_tag }} \
            --push \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  cashfolio-app-typecheck:
    name: "cashfolio-app: Typecheck"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: felixmokross/webplatform/.github/actions/setup@main
      - name: Install dependencies
        run: pnpm --filter cashfolio-app install
      - name: Generate Prisma Client
        run: pnpm --filter cashfolio-app exec prisma generate
      - name: Run typecheck in cashfolio-app
        run: pnpm --filter cashfolio-app typecheck

  cashfolio-app-unit-tests:
    name: "cashfolio-app: Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: felixmokross/webplatform/.github/actions/setup@main
      - name: Install dependencies
        run: pnpm --filter cashfolio-app install
      - name: Generate Prisma Client
        run: pnpm --filter cashfolio-app exec prisma generate
      - name: Run unit tests in cashfolio-app
        run: pnpm --filter cashfolio-app test

  cashfolio-redis-build-push:
    name: "cashfolio-redis: Build and Push"
    runs-on: ubuntu-latest
    needs: [version]
    outputs:
      image: ${{ steps.image-name.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - name: Get cashfolio-redis image name
        id: image-name
        run: |
          IMAGE_NAME=${{ vars.FLY_CASHFOLIO_REDIS_STAGING_APP }}
          IMAGE_TAG=v${{ needs.version.outputs.version_with_sha }}
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "image=registry.fly.io/$IMAGE_NAME:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
      - name: Build and push cashfolio-redis Docker image
        run: |
          flyctl deploy \
            --app ${{ steps.image-name.outputs.image_name }} \
            --config infra/cashfolio-redis/fly.build.toml \
            --build-only \
            --image-label ${{ steps.image-name.outputs.image_tag }} \
            --label org.opencontainers.image.version=${{ steps.image-name.outputs.image_tag }} \
            --push \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request'
    needs:
      - version
      - cashfolio-app-typecheck
      - cashfolio-app-unit-tests
      - cashfolio-app-build-push
    uses: ./.github/workflows/deploy-version.yml
    with:
      version_with_sha: ${{ needs.version.outputs.version_with_sha }}
      sha: ${{ needs.version.outputs.sha }}
      environment: staging
    secrets: inherit
