name: Deploy version
on:
  workflow_call:
    inputs:
      version_with_sha:
        type: string
        required: true
      sha:
        type: string
        required: true
      environment:
        type: string
        required: true
      high_availability:
        type: boolean
        default: true

env:
  NODE_VERSION: 22
  FLYCTL_VERSION: 0.3.95

jobs:
  cashfolio-app-deploy:
    name: "cashfolio-app: Deploy"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}-cashfolio-app
      url:
        https://${{ inputs.environment == 'preview' && format('{0}.fly.dev',
        steps.create-app.outputs.app_name) || vars.CANONICAL_HOSTNAME }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
        #   - name: Create app
        #     if: inputs.environment == 'preview'
        #     id: create-app
        #     run: |
        #       APP_NAME=${{ vars.FLY_PREVIEW_FRONTEND_APP_PREFIX }}-${{ inputs.sha }}
        #       CMS_APP_NAME=${{ vars.FLY_PREVIEW_CMS_APP_PREFIX }}-${{ inputs.sha }}

        #       echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
        #       echo "cms_app_name=$CMS_APP_NAME" >> $GITHUB_OUTPUT

        #       flyctl apps destroy --yes $APP_NAME || true

        #       flyctl apps create --name $APP_NAME --org ${{ vars.FLY_ORG }}
        #       flyctl secrets set \
        #         PAYLOAD_CMS_API_KEY=${{ secrets.PREVIEW_PAYLOAD_CMS_API_KEY }} \
        #         SESSION_SECRET=$(openssl rand -hex 12) \
        #         GOOGLE_MAPS_API_KEY="${{ secrets.PREVIEW_GOOGLE_MAPS_API_KEY }}" \
        #         REDIS_URL="${{ secrets.PREVIEW_REDIS_URL }}" \
        #         --app $APP_NAME --stage
        #     env:
        #       FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Prepare configuration file
        run: |
          envsubst \
              < apps/cashfolio-app/fly.template.toml \
              > apps/cashfolio-app/fly.generated.toml \

          echo "Generated configuration file:"
          cat apps/cashfolio-app/fly.generated.toml
        env:
          FLY_APP:
            ${{ inputs.environment == 'preview' &&
            steps.create-app.outputs.app_name || vars.FLY_APP }}
          FLY_PRIMARY_REGION: ${{ vars.FLY_PRIMARY_REGION }}
          FLY_MIN_MACHINES_RUNNING: ${{ vars.FLY_MIN_MACHINES_RUNNING }}
          FLY_MEMORY: ${{ vars.FLY_MEMORY }}
          FLY_CPU_KIND: ${{ vars.FLY_CPU_KIND }}
          FLY_CPUS: ${{ vars.FLY_CPUS }}
          CANONICAL_HOSTNAME:
            ${{ inputs.environment == 'preview' && format('https://{0}.fly.dev',
            steps.create-app.outputs.app_name) || vars.CANONICAL_HOSTNAME }}
      - name: Deploy cashfolio-app
        run: |
          flyctl deploy \
          --config apps/cashfolio-app/fly.generated.toml \
          --ha=${{ inputs.high_availability }} \
          --image registry.fly.io/${{ vars.FLY_CASHFOLIO_APP_STAGING_APP }}:v${{ inputs.version_with_sha }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
